title: Mustard Seed
description: |
  Boston University's Premier Christian A Cappella Group
owner: Julie Wang
first_published: 2021
email: julieewang822@gmail.com
baseurl: ''
url: ''
social:
  twitter: 'https://twitter.com/<username>'
  github: 'https://github.com/<username>'
  linkedin-square: 'https://linkedin.com/in/<username>'
  facebook-official: 'https://facebook.com/<username>'
  google-plus-square: 'https://plus.google.com/u/0/+<username>'
markdown: kramdown
